#%RAML 1.0

# AMWA NMOS Audo Channel Mapping Specification: Channel Mapping API
# (c) AMWA 2018

title: AMWA NMOS Audio Channel Mapping
baseUri: http://example.api.com/x-nmos/channelmapping/{version}
version: v1.0
mediaType: application/json

documentation:
  - title: Overview
    content: |
      The Audio Channel Mapping API is exposed by NMOS Devices as a standard control interface for management of audio matrix mapping inside Devices.
  - title: Further Documentation
    content: |
      Further normative documentation covering the behaviour of this API is contained in the [docs](../docs) folder of this repository.
/:
  displayName: Base
  get:
    responses:
      200:
        body:
          example: !include ../examples/base-get-200.json
/io:
  displayName: Input/Output view
  get:
    responses: 
      200:
        body:
          example: !include ../examples/io-get-200.json
          type: !include schemas/io-response-schema.json

/map:
  displayName: Map entity root
  get:
    responses:
      200:
        body:
          example: !include ../examples/map/map-root-get-200.json
  /staged:
    displayName: Staged mapping table
    get:
      responses:
        200:
          body:
            example: !include ../examples/map/map-tables-get-200.json
            type: !include schemas/map-tables-response-schema.json
    patch:
      body:
        example: !include ../examples/map/map-staged-patch-activate-immediate.json
        type: !include schemas/map-tables-request-schema.json
      responses: 
        200:
          body:
            example: !include ../examples/map/map-staged-patch-200.json
            type: !include schemas/map-tables-response-schema.json
        400:
          body:
            type: !include schemas/error.json
            example: !include ../examples/map/map-tables-patch-400.json
        423:
          description: >
          Returned when the resource is locked because an activation has been scheduled.
          A resource may be unlocked by setting `mode` in `activation` to `null`, which
          will cancel the pending activation. This may be done in the same request as a change
          to other parameters.
          body:
            type: !include schemas/error.json
            example: !include ../examples/map/map-tables-patch-423.json
        500:
          body:
            type: !include schemas/error.json
            example: !include ../examples/map/map-tables-patch-500.json
        404:
          description: Returned when the requested resource does not exist
    options:
      description: A pre-flight check generally used for Cross-Origin Resource Sharing (CORS) purposes
      responses:
        200:
        403:
  /active:
    displayName: Active mapping resource
    get:
      responses:
        200:
          body:
            example: !include ../examples/map/map-tables-get-200.json
            type: !include schemas/map-tables-response-schema.json
/inputs:
  displayName: Inputs
  get:
    description: List all inputs available
    responses:
      200:
        body:
          example: !include ../examples/inputs/inputs-root-get-200.json
          type: !include schemas/input-output-root-schema.json
  /{inputName}:
    get:
      responses:
        200:
          body:
            example: !include ../examples/inputs/input-name-root-get-200.json
        404:
          description: Returned when an the input name does not exist
    /caps:
      get:
        responses:
          200:
            body:
              example: !include ../examples/inputs/input-name-caps-200.json
              type: !include schemas/input-caps-response-schema.json
          404:
            description: Returned when the requested resource does not exist
    /parent:
      get:
        responses:
          200:
            body: 
              example: !include ../examples/inputs/input-name-parent-get-200.json
              type: !include schemas/input-parent-response-schema.json
          404:
            description: Returned when the requested resource does not exist
    /channels:
      get:
        responses: 
          200:
            body: 
              example: !include ../examples/inputs/input-name-channels-get-200.json
              type: !include schemas/input-channels-response-schema.json
          404:
            description: Returned when the requested resource does not exist
/outputs:
  displayName: Outputs
  get:
    description: List all outputs available
    responses: 
      200:
        body:
          example: !include ../examples/outputs/output-root-get-200.json
          type: !include schemas/input-output-root-schema.json
      404:
        description: Returned when the requested resource does not exist
  /{outputName}:
    get:
      responses:
        200:
          body:
            example: !include ../examples/outputs/output-name-root-get-200.json
        404:
          description: Returned when the requested resource does not exist
    /sourceid:
      get:
        responses: 
          200:
            body:
              example: !include ../examples/outputs/output-name-sourceid-get-200.json
              type: !include schemas/output-sourceID-response-schema.json
          404:
            description: Returned when the requested resource does not exist
    /channels:
      get:
        responses:
          200:
            body:
              example: !include ../examples/outputs/output-name-channels-get-200.json
              type: !include schemas/output-channels-response-schema.json
          404:
            description: Returned when the requested resource does not exist
    /caps:
      get:
        responses: 
          200:
            body:
              example: !include ../examples/outputs/output-name-caps-get-200.json
              type: !include schemas/output-caps-response-schema.json
